### PR TITLE
Nwhl storage related bugfixes

### LINKED ISSUE #165: [PE-D] Json file parsing bug?
When `addressbook.json` is invalid, the app correctly resets the contacts list. However, the appointment list still remains the same as the previous startup, even though the 3 James are gone from the list of contacts.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: koh-jx/ped#4

### LINKED ISSUE #173: [PE-D] Wrong documentation for editing the data file
The current data file is at the path [JAR file location]/data/addressbook.json while the documentation in the UG guides shows this:

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Ruofan1023/ped#7

### LINKED ISSUE #181: Storage to check time conflicts when parsing

### PR DESCRIPTION
**Pull request by nwhloo99**
Fixes #181 
Fixes #173 
Fixes #165

### CODE REVIEW

File: src/main/java/seedu/placebook/MainApp.java [hunk 1]
```diff
@@ -112,6 +99,21 @@ private Model initModelManager(Storage storage, ReadOnlyUserPrefs userPrefs) {
...
+            initialData = addressBookOptional.orElseGet(SampleDataUtil::getSampleAddressBook);
+        } catch (DataConversionException e) {
+            logger.warning("Data file not in the correct format. Will be starting with an empty AddressBook");
+            initialData = new AddressBook();
+        } catch (IOException e) {
+            logger.warning("Problem while reading from the file. Will be starting with an empty AddressBook");
+            initialData = new AddressBook();
+            initialSchedule = new Schedule();
+        }
+
```
Comment (YaleChen299) [inline src/main/java/seedu/placebook/MainApp.java:116]: this change in sequence might still result in valid schedule and empty addressbook? Is it that IOException is thrown when the addressbook is invalid? This might still left the problem where the addressbook does not corresponds to the schedule.

Comment (YaleChen299) [reply src/main/java/seedu/placebook/MainApp.java:116]: I have not investigate the trace, please correct me if I am wrong!

**Review by YaleChen299 — COMMENTED** [review]
Thanks for the contribution! Generally looks good. Left a few comments.

File: src/main/java/seedu/placebook/MainApp.java (hunk 1 above)
Comment (nwhloo99) [reply src/main/java/seedu/placebook/MainApp.java:116]: Okay I missed out the DataConversionException block, should add an additional line, initialSchedule = new Schedule() there

Comment (nwhloo99) [reply src/main/java/seedu/placebook/MainApp.java:116]: With this change, we will read data from json for schedule first, then if theres any error wipe only schedule. If there is no error we will have the correct schedule.

However, if we manage to get a correct schedule, but there is error in the AddressBook, we will wipe both addressbook and schedule, so there should be no problem where theres any appointments with people that dont exist.

File: src/test/data/JsonSerializableScheduleTest/typicalAppointmentSchedule.json [hunk 2]
```diff
@@ -23,8 +23,8 @@
     } ],
     "location" : "vivocity",
     "timePeriod" : {
-      "startDateTime" : "25-12-2021 1000",
-      "endDateTime" : "25-12-2021 1100"
+      "startDateTime" : "25-12-2021 1600",
+      "endDateTime" : "25-12-2021 1800"
     },
```
[the remark this answers is not in the document]
Comment (nwhloo99) [reply src/test/data/JsonSerializableScheduleTest/typicalAppointmentSchedule.json:28]: Yup I just saw your changes I will try take note when merging

File: src/main/java/seedu/placebook/MainApp.java (hunk 1 above)
Comment (YaleChen299) [reply src/main/java/seedu/placebook/MainApp.java:116]: Thanks for the explanation! That clear things a lot. May I ask will the loading of schedule loads those person in schedule to addressbook too?

Comment (nwhloo99) [reply src/main/java/seedu/placebook/MainApp.java:116]: No it doesnt, it will read separately because they are stored in different data files.

**Review by tchiong — APPROVED** [review]
LGTM
