### PR TITLE
Fix Ui bugs and add `uiStub` support

### LINKED ISSUE #142: [PE-D] Editing a person does not update their name in the appointment
In the below img both appointment 5,6 have Roger Lee (Person No. 5) as one of the attendees.

After issuing the command `edit 5 n/Jack Ryan`  to change the name of Person No.5 this change is not reflected in the appointment cards, which still show Roger Lee as one of the attendees.

Note: The dropdown list of contacts is correctly updated

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: dhshah1/ped#1

### LINKED ISSUE #149: [PE-D] Styling of confirmation popup for light theme
This is not a bug and just a suggestion.

Perhaps it would be nice if the confirmation pop up was also styled according to the light theme when thats being used.

Currently it seems follow only the dark theme, even if the app is in light theme mode.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: dhshah1/ped#8

### LINKED ISSUE #196: Need for UiStub support
There is a need for UiStub support to test delete and deleteApp

### PR DESCRIPTION
**Pull request by YaleChen299**
fixes #142 
fixes #149 
fixes #196

### CODE REVIEW

File: src/main/java/seedu/placebook/ui/ThemeManager.java [hunk 1]
```diff
@@ -7,14 +7,19 @@
 
 public class ThemeManager {
     private static final double size = 30;
+    private static final String darkThemeStylesheet = "view/DarkTheme.css";
```
Comment (nwhloo99) [inline src/main/java/seedu/placebook/ui/ThemeManager.java:10]: I think these final variables should be of the form DARK_THEME_STYLE_SHEET

File: src/test/java/seedu/placebook/logic/commands/AddAppCommandTest.java [hunk 2]
```diff
@@ -28,8 +29,11 @@
 import seedu.placebook.model.schedule.Appointment;
 import seedu.placebook.testutil.AppointmentBuilder;
 import seedu.placebook.testutil.PersonBuilder;
+import seedu.placebook.ui.Ui;
 
 public class AddAppCommandTest {
+    // default positive confirmation ui. This will not affect AddAppCommand
+    private static final Ui uiStub = UiStubFactory.getUiStub(true);
```
Comment (nwhloo99) [inline src/test/java/seedu/placebook/logic/commands/AddAppCommandTest.java:36]: Similarly should be named UI_STUB.

Also since none of the methods in the uiStub should be called here, maybe it is better to make another class in UiStubFactory for notCalledConfirmationUi, where all the methods would throw an exception for better testing.

Then instead of using a boolean for getUiStub can use another Enum.

File: src/test/java/seedu/placebook/logic/UiStubFactory.java [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+
+        }
+
+        @Override
+        public boolean showDeleteDialogAndWait(String contentText) {
+            return false;
+        }
+    }
+
+    private static final Ui POSITIVE_CONFIRMATION_UI = new positiveConfirmationUi();
```
Comment (nwhloo99) [inline src/test/java/seedu/placebook/logic/UiStubFactory.java:33]: Since these are static already, I am not sure if the above classes need to be static, please clarify if I am wrong

File: src/test/java/seedu/placebook/logic/commands/AddAppCommandTest.java (hunk 2 above)
Comment (nwhloo99) [reply src/test/java/seedu/placebook/logic/commands/AddAppCommandTest.java:36]: Im looking at the other commands, and since uiStubs have to be used everywhere now, is it possible to create the instances of UiStub in testUtil or somewhere similar to have better readability?

**Review by nwhloo99 — COMMENTED** [review]
I think generally ready to for merging, just some small comments. Also, might need to update the UML diagrams in the DG after this merge.

File: src/test/java/seedu/placebook/logic/commands/AddAppCommandTest.java (hunk 2 above)
Comment (YaleChen299) [reply src/test/java/seedu/placebook/logic/commands/AddAppCommandTest.java:36]: I think that instance is in the Factory, I am just getting them so that I dont have to write the long name later. Is this ok?

File: src/test/java/seedu/placebook/logic/UiStubFactory.java (hunk 3 above)
Comment (YaleChen299) [reply src/test/java/seedu/placebook/logic/UiStubFactory.java:33]: I think both will work? but I kinda dont want to give the impression that I can have different Factories so I chose to keep everything static here.

**Comment by YaleChen299** [comment]
There are some bugs in the test very hard to find, I just send here in case you encounter the same.
Some of those model are not modified correctly. When creating expected model, they create a new schedule but with the old appointment from the actual model, so when manipulating the expected model, the appointments gets manipulated as well, so this may affect the subsequent result of the actual model since they refer to the same appointments. 

a few ways to solve:
make appointment copy constructor, but this also needs to make copy for uniquepersonlist, address etc

make the typical appointment to create new instance every call, then call the typical appointment again

final decision:
use supplier for seeding data, so every call will give new instance.

File: src/main/java/seedu/placebook/model/ModelManager.java [hunk 4]
```diff
@@ -143,6 +143,7 @@ public boolean hasPerson(Person person) {
     @Override
     public void deletePerson(Person target) {
         addressBook.removePerson(target);
+        this.removePersonFromAppointments(target);
```
Comment (NecroWolf28) [inline src/main/java/seedu/placebook/model/ModelManager.java:146]: just checking, the order doesn't matter for these 2 methods cos removePersonFromAppointments doesn't use the addressbook? i just thought maybe there will be a NullPointerException

**Review by NecroWolf28 — COMMENTED** [review]
Seems fine but might need another reviewer

File: src/main/java/seedu/placebook/model/ModelManager.java (hunk 4 above)
Comment (nwhloo99) [reply src/main/java/seedu/placebook/model/ModelManager.java:146]: Should not matter, as the addressBook list and appointment list is separate.

**Review by nwhloo99 — APPROVED** [review]
LGTM

File: src/test/java/seedu/placebook/logic/commands/AddAppCommandTest.java (hunk 2 above)
Comment (nwhloo99) [reply src/test/java/seedu/placebook/logic/commands/AddAppCommandTest.java]: Oh ok should be fine

File: src/test/java/seedu/placebook/logic/UiStubFactory.java (hunk 3 above)
Comment (nwhloo99) [reply src/test/java/seedu/placebook/logic/UiStubFactory.java]: Makes sense
